steps:
  - uses: actions/checkout@v4

  - uses: subosito/flutter-action@v2
    with:
      channel: stable

  # Add this step to ensure Windows is configured
  - name: Add Windows support
    run: flutter create --platforms=windows .

  - run: flutter pub get
  - run: flutter build windows --release

  - uses: actions/upload-artifact@v4
    with:
      name: WindowsApp
      path: build/windows/runner/Release/
